### ISSUE TITLE
Visualizing distance map from surface loss

### ISSUE THREAD

**Issue by singhvishal0209** [LIVIAETS/boundary-loss#26]
The first image is the binary image and the second side is the distance map when I implement your distance map code used to calculate the surface loss. Is this how you wanted it to look like or am I making some mistake?

1)
![image](https://user-images.githubusercontent.com/40712087/84971231-e5825e80-b139-11ea-8ac7-7e0e234b8931.png)
2) 
![image](https://user-images.githubusercontent.com/40712087/84971152-c1bf1880-b139-11ea-8830-e34b256b8a61.png)

below is the code I used from your repository.

```python
 res = np.zeros_like(a_new)
 for c in range(C):
     posmask = a_new[c].astype(np.bool)

     if posmask.any():
         negmask = ~posmask
         res[c] = distance(negmask) * negmask - (distance(posmask) - 1) * posmask
```

**Comment by HKervadec** [comment]
Hello,

Something seems off with your generated distance map. It looks like it is computing it only on one axis (the horizontal one). 

What are the unique values of your `a_new` array, is it binary (`0` and `1` or some other value)? Notice that
```python
from scipy.ndimage import distance_transform_edt as distance
```
The documentation of that function is here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html

I invite you to experiment a bit with it directly, before generating the signed distance map.

Hoel
