### ISSUE TITLE
Help, about the output of net

### ISSUE THREAD

**Issue by wftubby** [LIVIAETS/boundary-loss#36]
Before posting, do check out the FAQ: https://github.com/LIVIAETS/boundary-loss#frequently-asked-question , the answer of your question might be there

is there a output of network to calculate the dice loss and boundary loss? or there are two output of network  to calculate the dice loss and boundary loss, respectively?

**Comment by haldunbalim** [comment]
Both are calculated using the same network output.

**Comment by wftubby** [comment]
Thanks

**Comment by HKervadec** [comment]
@haldunbalim is correct, both are computed from the network softmax probabilities
