### ISSUE TITLE
Boundary loss did not work

### ISSUE THREAD

**Issue by Jensen-Su** [LIVIAETS/boundary-loss#38]
Hi, I performed some experiments with boundary loss on my semantic segmentation task:

- exp1. with setting `1 * celoss + 1 * boundaryloss` and training from scratch, the` boundaryloss` decreased quickly from 7 to -6 in a few thousand iters, leaving `CEloss` decreasing very slowly to a high converging point.  The final IoU metric dropped 3~4 points compared with only using `celoss`.
- exp2. with setting `1 * celoss + 0.1 * boundaryloss` and training from scratch , the `boundaryloss` decreased quickly again, from 0.7 to -0.5 in a few thousand iters. and the `CEloss` decreased more quickly to an expected  lower converging point. The final IoU metric did not drop.
- exp3. with setting `1 * celoss + 0.5 * boundaryloss` and finetuning from a well-trained model, the `boundaryloss` was around -3 from the very beginning and did not decrease as training proceeds，which indicates that the `boundaryloss` for a model well-trained by `celoss` may be already saturate and may further implies that the `boundaryloss` will not work in my task.

Some information on my task:
- image semantic segmentation for driving scene.
- 10+ classes.
- severe class imbalance, with 99% v.s. 1% pixels for the most frequent class and the least frequent class.
- 3000 images with 720 * 1080 resolution.

Here are my questions:
 1. Does the indication/implication in exp3 reasonable?
 2. Could you provide some suggestions which may be useful for making the `boundaryloss` work?

Plus, following is a visualization of my implementation for the distance map:

following is `gt_mask`
![xx2](https://user-images.githubusercontent.com/17847306/117525034-0f16d380-aff3-11eb-9643-42f964c75986.png)
following is `distance map`
![dist2](https://user-images.githubusercontent.com/17847306/117525041-1a69ff00-aff3-11eb-85fa-fcd7bb5ab5d3.png)

**Comment by HKervadec** [comment]
Hi,

The distance map seems correct. Is there a relation to #26 ?

Your experiments seems sensible overall. As your setting is rather complex, I would proceed differently: I would try to add supervision with boundary loss one class after another. (I assume some classes would benefit more from the boundary loss, depending on their usual shape.) This way, it would be easier to diagnose and tune things. Once you manage to get some improvement by supervising (let's say) class 5, you could then add another one. And so on and so on.

Does that makes sense?

Hoel
