### ISSUE TITLE
Need to calculate the background-class loss for Multi-class Segment?

### ISSUE THREAD

**Issue by hei6775** [LIVIAETS/boundary-loss#39]
The content of your work is great and gave me a lot of ideas. But I have some questions that I haven't figured out. For multi-class segmentation, such as (ACDC dataset), will your dice loss and bl_loss calculate the four types of losses of 0, 1, 2, 3? Does not calculate the loss of 0 (background) to make the effect better? What kind of thinking are you based on?

**Comment by HKervadec** [comment]
Hi,

So far, I have experimented multi-class by [treating the background (class 0) as yet another class](https://github.com/LIVIAETS/boundary-loss/blob/master/acdc.make#L91). The rationale actually stems from the binary case. 

When there are only two classes, the background is the perfect negative of the foreground; therefore its distance map is simply the reverse of the other one, it doesn't bring much new value so we can skip it.

This property is obviously not true anymore in multi-class (at least in the general case), so I started by supervising the background. Skipping it might still work, but for other reasons (indirrect supervision), and it might vary depending on the task.

Does that answer your question?

Best,

Hoel
