### ISSUE TITLE
Does einsum really make the code easier to understand

### ISSUE THREAD

**Issue by milesial** [LIVIAETS/boundary-loss#43]
Hey,

I see that in the code for the loss you use the einsum `multipled = einsum("bkwh,bkwh->bkwh", pc, dc)`.

Also in the README, you explain that for 3D we need to change it to `multipled = einsum("bkxyz,bkxyz->bkxyz", pc, dc)`.

What is the point of using einsums if the underlying op is just `pc * dc`?

**Comment by HKervadec** [comment]
Hello,

I kept the einsum both for consistency with the rest of the code, and also to automatically document the code: it describes exactly the shape of each tensors used, and will error if fed something with a different shape.

I find it much easier to follow, especially when coming back to the codebase after a while. 

See also this older issue: https://github.com/LIVIAETS/boundary-loss/issues/3#issuecomment-450499897

Best,

Hoel

**Comment by milesial** [comment]
Ok, it makes sense, thanks!
