### ISSUE TITLE
ISLES 2018

### ISSUE THREAD

**Issue by YLyouthful** [LIVIAETS/boundary-loss#44]
Hello!

I downloaded the training data set from the ISLES2018 official website and found that it included:
* CT,
* CT_4DPWI, 
* CT_CNF, 
* CT_CBV, 
* CT_MTT, 
* CT_Tmax, and 
* OT. 
 
There is no corresponding DWI data, but I have seen the real DWI data paired with CT in your result. May I ask where to obtain the DWI data?Is it possible to share dataset？

Thank you!

**Comment by HKervadec** [comment]
Hello,

I just re-extracted the data, and I do not see any traces of the DWI. Where did you see the DWI in my results?

For context, here are the md5sum of the data that I use ; supposedly they come from the official website:
```
b6d16c456e173743e30a3fbdb3bd29a5  data/ISLES2018_Training.zip
932a493c105024942700fe589cd441a9  data/ISLES2018_Testing.zip
# Get data from https://www.smir.ch/ISLES/Start2018#download
# Requires registration and a few days to be approved.
```

Could you confirm that the md5sum of your data matches those? The exact script that I used for extraction and pre-processing are in the makefile:
```make
# Extraction of the zip
data/isles/TESTING data/isles/TRAINING: data/isles
data/isles: data/ISLES.lineage data/ISLES2018_Training.zip data/ISLES2018_Testing.zip
	md5sum -c $<
	rm -rf $@_tmp $@
	unzip -q $(word 2, $^) -d $@_tmp
	unzip -q $(word 3, $^) -d $@_tmp
	rm -r $@_tmp/__MACOSX
	rm -r $@_tmp/*/*/*CT_4DPWI*  # For space efficiency
	mv $@_tmp $@

# Slicing
data/ISLES/train/in_npy data/ISLES/val/in_npy: data/ISLES
data/ISLES: data/isles/TRAINING
	rm -rf $@_tmp $@
	PYTHONPATH="." python preprocess/slice_isles.py --source_dir $< --dest_dir $@_tmp --n_augment=0 --retain=20
	mv $@_tmp $@
data/ISLES/test: data/isles/TESTING
```

(You can check the meaning of the few automatic variables used [here](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html).)

Let me know,

Hoel
