### ISSUE TITLE
Question about the optional argument resolution in the dist_map_transform function

### ISSUE THREAD

**Issue by Allen-Zhou729** [LIVIAETS/boundary-loss#50]
Hi! Much thanks for sharing your code!
I am quite confused about this resolution argument  in the dist_map_transform function. I am not sure whether I should specify it in my code. Currently I have a label image with shape of 512x512(.png) feeding into the dist_map_transform function to compute the distance map, and do I need to specify the resolution argument(if yes, [1, 1] or [1, 1, 1])? Or just set it to None? If I change the resolution of the label image to 300x200, do I need to specify the resolution argument? And in what rules?
Thanks!

**Comment by HKervadec** [comment]
Hi,

Thanks for the interest.

The resolution is basically the pixels' width, which may vary across axis. It is used by the scipy function there: https://github.com/LIVIAETS/boundary-loss/blob/master/utils.py#L271

For reference, the documentation of https://scipy.github.io/devdocs/reference/generated/scipy.ndimage.distance_transform_edt.html:
> **sampling**: float, or sequence of float, optional
    Spacing of elements along each dimension. If a sequence, must be of length equal to the input rank; if a single number, this is used for all axes. If not specified, a grid spacing of unity is implied.


Basically, it enable the handling of special cases, where pixels width vary across axis (the basis is not orthonormal [1], only orthogonal): perhaps 1mm on the `x` axis, and 2mm on the `y` axis. But for the majority of cases, this number will be the same and you can safely ignore that.



> If I change the resolution of the label image to 300x200, do I need to specify the resolution argument?

I suppose you could define a resolution of `1x1.5`:
```python
>>> 1 / 300 * 300
1.0
>>> 1 / 200 * 300
1.5
```
Or go straight for `1.71x2.56`, assuming the original resolution was `1x1`:
```
>>> 512 / 300
1.7066666666666668
>>> 512 / 200
2.56
```


But perhaps it would not really be needed (in the sense, it would not impact the performances on your application). My advice would be to start without it, and add it if performances do not seem good.

Let me know,

Hoel

---
[1] https://en.wikipedia.org/wiki/Orthonormal_basis
