### ISSUE TITLE
Only using boundary loss leads to non convergence

### ISSUE THREAD

**Issue by liu-yx17** [LIVIAETS/boundary-loss#57]
Hello, I find that if I only use boundary loss as my loss function, the dice coefficient will gradually decay to zero. While when I only use dice loss for training and use boundary loss for just test, the boundary loss do decrease gradually. I don't know why. It seems that using boundary loss only is not enough.

**Comment by HKervadec** [comment]
(Sorry for the delayed reply. Somehow the Github notification for this repo are still broken on my side.)

Yes, this is discussed in the [paper](https://arxiv.org/pdf/1812.07032.pdf#page=12) Section 3.6.1. Note that this concerns only (so far as I've found) binary problems. This was discussed also several times in some issues on Github, but at the moment I do not have the time to dig them up, but please also see [this part of the readme](https://github.com/LIVIAETS/boundary-loss#multi-class-setting)
